studentdetails/Models/DBEntites/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace studentdetails.Models.DBEntites
{
    public class Student
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Column(TypeName ="varchar(50)")]
        public string FName { get; set; }
        public string LName { get; set; }
        public DateTime DOB { get; set; }
        public string address { get; set; }


    }
}

studentdetails/Models/ErrorViewModel.cs
using System;

namespace studentdetails.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

studentdetails/Models/Studentviewmodel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace studentdetails.Models
{
    public class Studentviewmodel
    {
        public int Id { get; set; }
        [DisplayName("FName")]
        public string FName { get; set; }
        [DisplayName("LName")]
        public string LName { get; set; }
        [DisplayName("DOB")]
        public DateTime DOB { get; set; }
        [DisplayName("address")]
        public string address { get; set; }
        [DisplayName("Name")]
        public string fullname { 
            get { return FName + " " + LName; } 
        }

    }
}

studentdetails/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using studentdetails.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace studentdetails.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

studentdetails/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using studentdetails.DAL;
using studentdetails.Models;
using studentdetails.Models.DBEntites;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace studentdetails.Controllers
{
    public class StudentController : Controller
    {
        private readonly studentDbContext _context;

        public StudentController(studentDbContext context)
        {
            this._context = context;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var student = _context.students.ToList();
            List<Studentviewmodel> studentsList = new List<Studentviewmodel>();

            if (student != null)
            {
                foreach(var studen in student)
                {
                    var Studentviewmodel = new Studentviewmodel()
                    {
                        Id = studen.Id,
                        FName = studen.FName,
                        LName =  studen.LName,
                        DOB = studen.DOB,
                        address = studen.address
                    };
                    studentsList.Add(Studentviewmodel);
                }
                return View(studentsList);
            }
            return View(studentsList);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Studentviewmodel studentdata)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var std = new Student()
                    {
                        Id = studentdata.Id,
                        FName = studentdata.FName,
                        LName = studentdata.LName,
                        DOB = studentdata.DOB,
                        address = studentdata.address
                    };
                    _context.students.Add(std);
                    _context.SaveChanges();
                    TempData["successMessage"] = "student data created successfully.";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["errorMessage"] = "Model data is not valid.";
                    return View();
                }
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }
        }
    }
}

studentdetails/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

studentdetails/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - studentdetails</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">studentdetails</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student Details</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - studentdetails - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/js/custom.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

studentdetails/Views/Student/Create.cshtml
@model studentdetails.Models.Studentviewmodel
@{
    ViewData["Title"] = "Create student";
    var errorMessage = TempData["errorMesage"]?.ToString();
}

<h3>@ViewData["Title"]</h3>
<hr />
@if (!string.IsNullOrWhiteSpace(@errorMessage)){
<div class="alert alert-danger">
    <strong>Error!</strong>@errorMessage
    <button type="button" class="btn-close float-end" data-bs-dismiss="alert"></button>
</div>
}
<form action="Create" method="post">
    <div class="mb-3">
        <label class="form-label">Id</label>
        <input type="number" class="form-control" asp-for="Id" />
        <span asp-validation-for="Id" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">FName</label>
        <input type="text" class="form-control" asp-for="FName" />
        <span asp-validation-for="FName" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">LName</label>
        <input type="text" class="form-control" asp-for="LName" />
        <span asp-validation-for="LName" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">DOB</label>
        <input type="date" class="form-control" asp-for="DOB" />
        <span asp-validation-for="DOB" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">address</label>
        <input type="text" class="form-control" asp-for="address" />
        <span asp-validation-for="address" class="text-danger"></span>
    </div>
    <div class="d-grid">
        <button type="submit" class="btn btn-primary">
            submit
        </button>
    </div>
</form>

studentdetails/Views/Student/Index.cshtml
@model List<studentdetails.Models.Studentviewmodel>
@{
        ViewData["Title"] = "Student details";
        var successMessage = TempData["successMessage"]?.ToString();
        var errorMessage = TempData["errorMessage"]?.ToString();
}

<h3>@ViewData["Title"]</h3>
<hr />
@if(!string.IsNullOrWhiteSpace(@successMessage)){
    <div class="alert alert-success">
        <strong>Success!</strong>@successMessage
    </div>
    <button type="button" class="btn-close float-end" data-bs-dismiss="Alert"></button>
}
else if(!string.IsNullOrWhiteSpace (@errorMessage)){
<div class="alert alert-danger">
    <strong>Error!</strong>@errorMessage
</div>
<button type="button" class="btn-close float-end" data-bs-dismiss="Alert"></button>
}
<form>
    <button asp-action="Create" class="btn btn-primary mb-3">Create Student</button>
    <table class="table-responsive table-hover table-bordered">
        <thead>
            <tr class="table-active">
                <th>Id</th>
                <th>Name</th>
                <th>Date-of-Birth</th>
                <th>Address</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                @foreach (var student in Model)
                {
                    <tr>
                        <td>
                            @student.Id
                        </td>
                        <td>
                            @student.fullname
                        </td>
                        <td>
                            @student.DOB
                        </td>
                        <td>
                            @student.address
                        </td>

                        <td>
                            <div class="btn-group btn-group-sm">
                                <a asp-controller="Student" asp-action="Edit" asp-route-Id="@student.Id"
                                   class="btn btn-primary">Edit</a>
                                <a asp-controller="Student" asp-action="Delete" asp-route-Id="@student.Id"
                                   class="btn btn-danger">Delete</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="5">
                        <div>
                            No Students available at this moment!
                        </div>

                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>